version: '3.8'

services:
  spec:
    build:
      context: ./spec
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./spec:/openapi
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    networks:
      - app-network
    command: go run .

networks:
  app-network:
    driver: bridge
